### ISSUE TITLE
Moved permanently

### ISSUE THREAD

**Issue by ImGek** [janko-m/down#20]
Hi, I'm using Down to download automatically some files from my webserver... Some of these have spaces in the name, so I replaced all spaces with `%20`. By pasting the URL in the browser I get the file downloading, but when using `Down.download` I get a `ResponseError - 301 Moved Permanently` error from the gem. How can I fix it?

**Comment by janko-m** [comment]
Hmm, Down should automatically follow up to 2 redirects. This means that even if there are too many redirects, you should get a `TooManyRedirects` exception, not `ResponseError`. Which Down version are you using? Can you give me an example URL for which you get this error?

**Comment by ImGek** [comment]
I sent the example URL to your email, and I also explained why there

Anyway, the version is 4.5.0

**Comment by janko-m** [comment]
The issue was that the server returned an invalid redirect URI, but this wasn't communicated in the error message. I pushed now a fix that raises `ResponseError – Invalid Redirect URI: ...` to make it clear why Down/open-uri couldn't follow the redirect.
