### ISSUE TITLE
Suggest using addressable

### ISSUE THREAD

**Issue by linyaoli** [janko-m/down#22]
Hi,

```
Down::InvalidUrl
/usr/local/bundle/gems/down-4.5.0/lib/down/net_http.rb:236:in `rescue in ensure_uri'
/usr/local/bundle/gems/down-4.5.0/lib/down/net_http.rb:231:in `ensure_uri'
/usr/local/bundle/gems/down-4.5.0/lib/down/net_http.rb:65:in `download'
/usr/local/bundle/gems/down-4.5.0/lib/down/backend.rb:13:in `download'
```
the standard URI lib used by `down` cannot parse URLs with some bizarre characters, such as `[`.
Please consider to use https://github.com/sporkmonger/addressable, if you don't mind I can also make a PR for it.

Thanks in advance.

**Comment by janko-m** [comment]
Hey @linyaoli, that is a known issue, it's definitely a limitation of the built-in URI standard library. So far I was reluctant to use Addressable, as I go the impression that it was a relatively heavy gem, and the goal of `down` is to be lightweight.

However, for reliability I think the ends justify the means, so I've decided that I'm ok with it being added after all.

I think we can do it in a way that we call `Addressable::URI#normalize!` and pass the normalized URI further.

```rb
require "addressable/uri"

url = Addressable::URI.parse(url).normalize!.to_s
# ...
```

Feel free to open a PR for this.

**Comment by janko-m** [comment]
Implemented in https://github.com/janko-m/down/commit/17642486db34075addc681e8c4ea0f2e8ea53eb6.
