### ISSUE TITLE
Skip download if destination already has file? 

### ISSUE THREAD

**Issue by matthoey-okta** [janko-m/down#25]
Is this built in? If not it looks like you can use open to inspect headers to get checksums (artifactory does this)

**Comment by janko-m** [comment]
Are you taking about when explicitly specifying the `:destination` path? No, it will always overwrite the file if it exists. What you're describing is most likely out of scope of this gem and should be implemented on higher level, e.g:

```rb
io = Down.open(url)
basename = io.data[:headers]["Content-MD5"]
destination = "#{directory}/#{basename}"
IO.copy_stream(io, destination) unless File.exists?(destination)
io.close
```

**Comment by matthoey-okta** [comment]
Fair enough. Thanks for replying so fast!
