### ISSUE TITLE
Only changed README.md but build of travis-ci failed, anyone knows why?

### ISSUE THREAD

**Issue by liukgg** [janko-m/down#6]
The detail is here:  https://github.com/janko-m/down/pull/5
I only changed README.md but build of travis-ci failed.Does anyone know why?
Any help is appreciated.Thanks!

**Comment by janko-m** [comment]
Yes, it's a known failure, this one test passes locally but fails on Travis, I need to find a way to fix it :smiley:

**Comment by liukgg** [comment]
Thank you for your reply!
